"""
Dashboard Client
"""
from __future__ import annotations
__all__: list[str] = ['DashboardClient']
class DashboardClient:
    def __init__(self, hostname: str, port: int = 29999, verbose: bool = False) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def addToLog(self, arg0: str) -> None:
        ...
    def brakeRelease(self) -> None:
        ...
    def closePopup(self) -> None:
        ...
    def closeSafetyPopup(self) -> None:
        ...
    def connect(self, timeout_ms: int = 2000) -> None:
        ...
    def disconnect(self) -> None:
        ...
    def getLoadedProgram(self) -> str:
        ...
    def getRobotModel(self) -> str:
        ...
    def getSerialNumber(self) -> str:
        ...
    def isConnected(self) -> bool:
        ...
    def isInRemoteControl(self) -> bool:
        ...
    def isProgramSaved(self) -> bool:
        ...
    def loadURP(self, arg0: str) -> None:
        ...
    def pause(self) -> None:
        ...
    def play(self) -> None:
        ...
    def polyscopeVersion(self) -> str:
        ...
    def popup(self, arg0: str) -> None:
        ...
    def powerOff(self) -> None:
        ...
    def powerOn(self) -> None:
        ...
    def programState(self) -> str:
        ...
    def quit(self) -> None:
        ...
    def receive(self) -> str:
        ...
    def restartSafety(self) -> None:
        ...
    def robotmode(self) -> str:
        ...
    def running(self) -> bool:
        ...
    def safetymode(self) -> str:
        ...
    def safetystatus(self) -> str:
        ...
    def send(self, arg0: str) -> None:
        ...
    def setUserRole(self, arg0: ...) -> None:
        ...
    def shutdown(self) -> None:
        ...
    def stop(self) -> None:
        ...
    def unlockProtectiveStop(self) -> None:
        ...
