"""
Script Client
"""
from __future__ import annotations
import typing
__all__: list[str] = ['ScriptClient']
class ScriptClient:
    def __init__(self, hostname: str, major_control_version: int, minor_control_version: int, port: int = 30002, verbose: bool = False) -> None:
        ...
    def __repr__(self) -> str:
        ...
    def connect(self) -> None:
        ...
    def disconnect(self) -> None:
        ...
    def getScript(self) -> str:
        ...
    def isConnected(self) -> bool:
        ...
    @typing.overload
    def sendScript(self) -> bool:
        ...
    @typing.overload
    def sendScript(self, arg0: str) -> bool:
        ...
    def sendScriptCommand(self, arg0: str) -> bool:
        ...
    def setScriptFile(self) -> bool:
        ...
